<<<<<<< HEAD
version: '3.8'
services:
  sample_app:
    build: ./sample_app
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
=======
# Docker Compose file content as defined in the repo-ready document.version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: auto-nginx
>>>>>>> b70b3389ce664d6cb78329380699c513a2175ff0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
<<<<<<< HEAD
    depends_on:
      - sample_app

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
=======

  sample_app:
    build: ./sample_app
    container_name: auto-sample-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus:latest
    container_name: auto-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
>>>>>>> b70b3389ce664d6cb78329380699c513a2175ff0
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
<<<<<<< HEAD
=======
    container_name: auto-grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
>>>>>>> b70b3389ce664d6cb78329380699c513a2175ff0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
